# Generated by Django 4.2.7 on 2025-06-01 17:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True)),
                ('keywords', models.TextField(blank=True)),
                ('url', models.URLField(max_length=2000)),
                ('scraped_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('headings', models.JSONField(default=list)),
                ('bold_texts', models.JSONField(default=list)),
                ('important_paragraphs', models.JSONField(default=list)),
                ('images', models.JSONField(default=list)),
                ('links', models.JSONField(default=list)),
            ],
            options={
                'verbose_name': 'Scraped Data',
                'verbose_name_plural': 'Scraped Data',
                'ordering': ['-created_at'],
            },
        ),
    ]
